// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetInvestigationMonsterRsp.proto

package emu.grasscutter.net.proto;

public final class GetInvestigationMonsterRspOuterClass {
  private GetInvestigationMonsterRspOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetInvestigationMonsterRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetInvestigationMonsterRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 retcode = 6;</code>
     * @return The retcode.
     */
    int getRetcode();

    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    java.util.List<emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster> 
        getUnk3300EEBEOCMAIKNList();
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster getUnk3300EEBEOCMAIKN(int index);
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    int getUnk3300EEBEOCMAIKNCount();
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    java.util.List<? extends emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder> 
        getUnk3300EEBEOCMAIKNOrBuilderList();
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder getUnk3300EEBEOCMAIKNOrBuilder(
        int index);

    /**
     * <code>bool isForMark = 11;</code>
     * @return The isForMark.
     */
    boolean getIsForMark();
  }
  /**
   * <pre>
   *enum ONMJIJLGELG {
   *	option allow_alias= true;
   *	NONE = 0;
   *	PEPPOHPHJOJ = 1927;
   *	DCDNILFDFLB = 0;
   *	NNBKOLMPOEA = 1;
   *	EAJIABGAOCI = 1;
   *}
   * </pre>
   *
   * Protobuf type {@code GetInvestigationMonsterRsp}
   */
  public static final class GetInvestigationMonsterRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetInvestigationMonsterRsp)
      GetInvestigationMonsterRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetInvestigationMonsterRsp.newBuilder() to construct.
    private GetInvestigationMonsterRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInvestigationMonsterRsp() {
      unk3300EEBEOCMAIKN_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetInvestigationMonsterRsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetInvestigationMonsterRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                unk3300EEBEOCMAIKN_ = new java.util.ArrayList<emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster>();
                mutable_bitField0_ |= 0x00000001;
              }
              unk3300EEBEOCMAIKN_.add(
                  input.readMessage(emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.parser(), extensionRegistry));
              break;
            }
            case 48: {

              retcode_ = input.readInt32();
              break;
            }
            case 88: {

              isForMark_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          unk3300EEBEOCMAIKN_ = java.util.Collections.unmodifiableList(unk3300EEBEOCMAIKN_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.internal_static_GetInvestigationMonsterRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.internal_static_GetInvestigationMonsterRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp.class, emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp.Builder.class);
    }

    public static final int RETCODE_FIELD_NUMBER = 6;
    private int retcode_;
    /**
     * <code>int32 retcode = 6;</code>
     * @return The retcode.
     */
    @java.lang.Override
    public int getRetcode() {
      return retcode_;
    }

    public static final int UNK3300_EEBEOCMAIKN_FIELD_NUMBER = 2;
    private java.util.List<emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster> unk3300EEBEOCMAIKN_;
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    @java.lang.Override
    public java.util.List<emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster> getUnk3300EEBEOCMAIKNList() {
      return unk3300EEBEOCMAIKN_;
    }
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder> 
        getUnk3300EEBEOCMAIKNOrBuilderList() {
      return unk3300EEBEOCMAIKN_;
    }
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    @java.lang.Override
    public int getUnk3300EEBEOCMAIKNCount() {
      return unk3300EEBEOCMAIKN_.size();
    }
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster getUnk3300EEBEOCMAIKN(int index) {
      return unk3300EEBEOCMAIKN_.get(index);
    }
    /**
     * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder getUnk3300EEBEOCMAIKNOrBuilder(
        int index) {
      return unk3300EEBEOCMAIKN_.get(index);
    }

    public static final int ISFORMARK_FIELD_NUMBER = 11;
    private boolean isForMark_;
    /**
     * <code>bool isForMark = 11;</code>
     * @return The isForMark.
     */
    @java.lang.Override
    public boolean getIsForMark() {
      return isForMark_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < unk3300EEBEOCMAIKN_.size(); i++) {
        output.writeMessage(2, unk3300EEBEOCMAIKN_.get(i));
      }
      if (retcode_ != 0) {
        output.writeInt32(6, retcode_);
      }
      if (isForMark_ != false) {
        output.writeBool(11, isForMark_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < unk3300EEBEOCMAIKN_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, unk3300EEBEOCMAIKN_.get(i));
      }
      if (retcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, retcode_);
      }
      if (isForMark_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, isForMark_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp other = (emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp) obj;

      if (getRetcode()
          != other.getRetcode()) return false;
      if (!getUnk3300EEBEOCMAIKNList()
          .equals(other.getUnk3300EEBEOCMAIKNList())) return false;
      if (getIsForMark()
          != other.getIsForMark()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RETCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRetcode();
      if (getUnk3300EEBEOCMAIKNCount() > 0) {
        hash = (37 * hash) + UNK3300_EEBEOCMAIKN_FIELD_NUMBER;
        hash = (53 * hash) + getUnk3300EEBEOCMAIKNList().hashCode();
      }
      hash = (37 * hash) + ISFORMARK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsForMark());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *enum ONMJIJLGELG {
     *	option allow_alias= true;
     *	NONE = 0;
     *	PEPPOHPHJOJ = 1927;
     *	DCDNILFDFLB = 0;
     *	NNBKOLMPOEA = 1;
     *	EAJIABGAOCI = 1;
     *}
     * </pre>
     *
     * Protobuf type {@code GetInvestigationMonsterRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetInvestigationMonsterRsp)
        emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.internal_static_GetInvestigationMonsterRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.internal_static_GetInvestigationMonsterRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp.class, emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUnk3300EEBEOCMAIKNFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        retcode_ = 0;

        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          unk3300EEBEOCMAIKN_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          unk3300EEBEOCMAIKNBuilder_.clear();
        }
        isForMark_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.internal_static_GetInvestigationMonsterRsp_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp build() {
        emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp buildPartial() {
        emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp result = new emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp(this);
        int from_bitField0_ = bitField0_;
        result.retcode_ = retcode_;
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            unk3300EEBEOCMAIKN_ = java.util.Collections.unmodifiableList(unk3300EEBEOCMAIKN_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.unk3300EEBEOCMAIKN_ = unk3300EEBEOCMAIKN_;
        } else {
          result.unk3300EEBEOCMAIKN_ = unk3300EEBEOCMAIKNBuilder_.build();
        }
        result.isForMark_ = isForMark_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp) {
          return mergeFrom((emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp other) {
        if (other == emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp.getDefaultInstance()) return this;
        if (other.getRetcode() != 0) {
          setRetcode(other.getRetcode());
        }
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          if (!other.unk3300EEBEOCMAIKN_.isEmpty()) {
            if (unk3300EEBEOCMAIKN_.isEmpty()) {
              unk3300EEBEOCMAIKN_ = other.unk3300EEBEOCMAIKN_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUnk3300EEBEOCMAIKNIsMutable();
              unk3300EEBEOCMAIKN_.addAll(other.unk3300EEBEOCMAIKN_);
            }
            onChanged();
          }
        } else {
          if (!other.unk3300EEBEOCMAIKN_.isEmpty()) {
            if (unk3300EEBEOCMAIKNBuilder_.isEmpty()) {
              unk3300EEBEOCMAIKNBuilder_.dispose();
              unk3300EEBEOCMAIKNBuilder_ = null;
              unk3300EEBEOCMAIKN_ = other.unk3300EEBEOCMAIKN_;
              bitField0_ = (bitField0_ & ~0x00000001);
              unk3300EEBEOCMAIKNBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUnk3300EEBEOCMAIKNFieldBuilder() : null;
            } else {
              unk3300EEBEOCMAIKNBuilder_.addAllMessages(other.unk3300EEBEOCMAIKN_);
            }
          }
        }
        if (other.getIsForMark() != false) {
          setIsForMark(other.getIsForMark());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retcode_ ;
      /**
       * <code>int32 retcode = 6;</code>
       * @return The retcode.
       */
      @java.lang.Override
      public int getRetcode() {
        return retcode_;
      }
      /**
       * <code>int32 retcode = 6;</code>
       * @param value The retcode to set.
       * @return This builder for chaining.
       */
      public Builder setRetcode(int value) {
        
        retcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retcode = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetcode() {
        
        retcode_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster> unk3300EEBEOCMAIKN_ =
        java.util.Collections.emptyList();
      private void ensureUnk3300EEBEOCMAIKNIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          unk3300EEBEOCMAIKN_ = new java.util.ArrayList<emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster>(unk3300EEBEOCMAIKN_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder> unk3300EEBEOCMAIKNBuilder_;

      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster> getUnk3300EEBEOCMAIKNList() {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          return java.util.Collections.unmodifiableList(unk3300EEBEOCMAIKN_);
        } else {
          return unk3300EEBEOCMAIKNBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public int getUnk3300EEBEOCMAIKNCount() {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          return unk3300EEBEOCMAIKN_.size();
        } else {
          return unk3300EEBEOCMAIKNBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster getUnk3300EEBEOCMAIKN(int index) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          return unk3300EEBEOCMAIKN_.get(index);
        } else {
          return unk3300EEBEOCMAIKNBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder setUnk3300EEBEOCMAIKN(
          int index, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster value) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3300EEBEOCMAIKNIsMutable();
          unk3300EEBEOCMAIKN_.set(index, value);
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder setUnk3300EEBEOCMAIKN(
          int index, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder builderForValue) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          ensureUnk3300EEBEOCMAIKNIsMutable();
          unk3300EEBEOCMAIKN_.set(index, builderForValue.build());
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder addUnk3300EEBEOCMAIKN(emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster value) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3300EEBEOCMAIKNIsMutable();
          unk3300EEBEOCMAIKN_.add(value);
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder addUnk3300EEBEOCMAIKN(
          int index, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster value) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnk3300EEBEOCMAIKNIsMutable();
          unk3300EEBEOCMAIKN_.add(index, value);
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder addUnk3300EEBEOCMAIKN(
          emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder builderForValue) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          ensureUnk3300EEBEOCMAIKNIsMutable();
          unk3300EEBEOCMAIKN_.add(builderForValue.build());
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder addUnk3300EEBEOCMAIKN(
          int index, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder builderForValue) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          ensureUnk3300EEBEOCMAIKNIsMutable();
          unk3300EEBEOCMAIKN_.add(index, builderForValue.build());
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder addAllUnk3300EEBEOCMAIKN(
          java.lang.Iterable<? extends emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster> values) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          ensureUnk3300EEBEOCMAIKNIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, unk3300EEBEOCMAIKN_);
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder clearUnk3300EEBEOCMAIKN() {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          unk3300EEBEOCMAIKN_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public Builder removeUnk3300EEBEOCMAIKN(int index) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          ensureUnk3300EEBEOCMAIKNIsMutable();
          unk3300EEBEOCMAIKN_.remove(index);
          onChanged();
        } else {
          unk3300EEBEOCMAIKNBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder getUnk3300EEBEOCMAIKNBuilder(
          int index) {
        return getUnk3300EEBEOCMAIKNFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder getUnk3300EEBEOCMAIKNOrBuilder(
          int index) {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          return unk3300EEBEOCMAIKN_.get(index);  } else {
          return unk3300EEBEOCMAIKNBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public java.util.List<? extends emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder> 
           getUnk3300EEBEOCMAIKNOrBuilderList() {
        if (unk3300EEBEOCMAIKNBuilder_ != null) {
          return unk3300EEBEOCMAIKNBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(unk3300EEBEOCMAIKN_);
        }
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder addUnk3300EEBEOCMAIKNBuilder() {
        return getUnk3300EEBEOCMAIKNFieldBuilder().addBuilder(
            emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.getDefaultInstance());
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder addUnk3300EEBEOCMAIKNBuilder(
          int index) {
        return getUnk3300EEBEOCMAIKNFieldBuilder().addBuilder(
            index, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.getDefaultInstance());
      }
      /**
       * <code>repeated .InvestigationMonster Unk3300_EEBEOCMAIKN = 2;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder> 
           getUnk3300EEBEOCMAIKNBuilderList() {
        return getUnk3300EEBEOCMAIKNFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder> 
          getUnk3300EEBEOCMAIKNFieldBuilder() {
        if (unk3300EEBEOCMAIKNBuilder_ == null) {
          unk3300EEBEOCMAIKNBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonster.Builder, emu.grasscutter.net.proto.InvestigationMonsterOuterClass.InvestigationMonsterOrBuilder>(
                  unk3300EEBEOCMAIKN_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          unk3300EEBEOCMAIKN_ = null;
        }
        return unk3300EEBEOCMAIKNBuilder_;
      }

      private boolean isForMark_ ;
      /**
       * <code>bool isForMark = 11;</code>
       * @return The isForMark.
       */
      @java.lang.Override
      public boolean getIsForMark() {
        return isForMark_;
      }
      /**
       * <code>bool isForMark = 11;</code>
       * @param value The isForMark to set.
       * @return This builder for chaining.
       */
      public Builder setIsForMark(boolean value) {
        
        isForMark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isForMark = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsForMark() {
        
        isForMark_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetInvestigationMonsterRsp)
    }

    // @@protoc_insertion_point(class_scope:GetInvestigationMonsterRsp)
    private static final emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp();
    }

    public static emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetInvestigationMonsterRsp>
        PARSER = new com.google.protobuf.AbstractParser<GetInvestigationMonsterRsp>() {
      @java.lang.Override
      public GetInvestigationMonsterRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetInvestigationMonsterRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetInvestigationMonsterRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetInvestigationMonsterRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.GetInvestigationMonsterRspOuterClass.GetInvestigationMonsterRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetInvestigationMonsterRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetInvestigationMonsterRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n GetInvestigationMonsterRsp.proto\032\032Inve" +
      "stigationMonster.proto\"t\n\032GetInvestigati" +
      "onMonsterRsp\022\017\n\007retcode\030\006 \001(\005\0222\n\023Unk3300" +
      "_EEBEOCMAIKN\030\002 \003(\0132\025.InvestigationMonste" +
      "r\022\021\n\tisForMark\030\013 \001(\010B\033\n\031emu.grasscutter." +
      "net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          emu.grasscutter.net.proto.InvestigationMonsterOuterClass.getDescriptor(),
        });
    internal_static_GetInvestigationMonsterRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetInvestigationMonsterRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetInvestigationMonsterRsp_descriptor,
        new java.lang.String[] { "Retcode", "Unk3300EEBEOCMAIKN", "IsForMark", });
    emu.grasscutter.net.proto.InvestigationMonsterOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
